// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountStudent(ctx context.Context) (int64, error)
	DeleteStudentByID(ctx context.Context, id uuid.UUID) error
	GetStudentByID(ctx context.Context, id uuid.UUID) (Student, error)
	Liststudents(ctx context.Context, name sql.NullString) ([]Student, error)
	UpdateDescriptionStudent(ctx context.Context, arg UpdateDescriptionStudentParams) error
}

var _ Querier = (*Queries)(nil)
