// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountStudent(ctx context.Context) (int64, error)
	DeleteStudentByID(ctx context.Context, id uuid.UUID) error
	GetStudentByID(ctx context.Context, id uuid.UUID) (Student, error)
	InsertStudent(ctx context.Context, arg InsertStudentParams) (Student, error)
	Liststudents(ctx context.Context, arg ListstudentsParams) ([]Student, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) error
}

var _ Querier = (*Queries)(nil)
